/**
 * TSW6 Special Edition route definitions.
 * Stations are listed in the natural "outbound" direction for each line.
 */
export const ROUTES = [
  {
    id: 'morristown_line',
    name: 'Morristown Line',
    country: 'US',
    stations: [
      'New York Penn Station',
      'Newark Penn Station',
      'Newark Broad Street',
      'Highland Avenue',
      'Mountain Station',
      'Orange',
      'South Orange',
      'Maplewood',
      'Millburn',
      'Short Hills',
      'Summit',
      'New Providence',
      'Murray Hill',
      'Berkeley Heights',
      'Gillette',
      'Stirling',
      'Millington',
      'Lyons',
      'Basking Ridge',
      'Bernardsville',
      'Far Hills',
      'Peapack',
      'Gladstone',
    ],
  },
  {
    id: 'morristown_line_main',
    name: 'Morristown Line (Main Branch)',
    country: 'US',
    stations: [
      'New York Penn Station',
      'Newark Penn Station',
      'Newark Broad Street',
      'Highland Avenue',
      'Mountain Station',
      'Orange',
      'South Orange',
      'Maplewood',
      'Millburn',
      'Short Hills',
      'Summit',
      'Chatham',
      'Madison',
      'Convent Station',
      'Morris Plains',
      'Morristown',
      'Mount Tabor',
      'Denville',
      'Dover',
      'Rockaway',
      'Mount Arlington',
      'Lake Hopatcong',
      'Kingsland',
      'Landing',
      'Lake Hopatcong',
      'Netcong',
      'Hackettstown',
    ],
  },
  {
    id: 'dresden_leipzig',
    name: 'Dresden–Leipzig',
    country: 'DE',
    stations: [
      'Dresden Hbf',
      'Dresden-Neustadt',
      'Radebeul Ost',
      'Coswig (b Dresden)',
      'Weinböhla',
      'Priestewitz',
      'Riesa',
      'Strehla',
      'Borsdorf (b Leipzig)',
      'Leipzig-Thekla',
      'Leipzig-Mockau',
      'Leipzig Hbf',
    ],
  },
  {
    id: 'mannheim_kaiserslautern',
    name: 'Mannheim–Kaiserslautern',
    country: 'DE',
    stations: [
      'Mannheim Hbf',
      'Ludwigshafen (Rhein) Hbf',
      'Ludwigshafen-Oggersheim',
      'Limburgerhof',
      'Schifferstadt',
      'Böhl-Iggelheim',
      'Neuhofen (Pfalz)',
      'Neustadt (Weinstr) Hbf',
      'Böbingen (Pfalz)',
      'Elmstein',
      'Hochspeyer',
      'Frankenstein (Pfalz)',
      'Kaiserslautern Hbf',
    ],
  },
  {
    id: 'boston_worcester',
    name: 'Boston–Worcester',
    country: 'US',
    stations: [
      'Boston South Station',
      'Back Bay',
      'Newtonville',
      'West Newton',
      'Auburndale',
      'Wellesley Farms',
      'Wellesley Hills',
      'Wellesley Square',
      'Natick',
      'West Natick',
      'Framingham',
      'Ashland',
      'Southborough',
      'Westborough',
      'Grafton',
      'Worcester Union Station',
    ],
  },
  {
    id: 'riviera_line',
    name: 'Riviera Line',
    country: 'UK',
    stations: [
      'Exeter St Davids',
      'Exeter Central',
      'Polsloe Bridge',
      'Digby & Sowton',
      'Cranbrook',
      'Newcourt',
      'Topsham',
      'Exton',
      'Lympstone Village',
      'Lympstone Commando',
      'Exmouth',
      'Dawlish Warren',
      'Dawlish',
      'Teignmouth',
      'Newton Abbot',
      'Torre',
      'Torquay',
      'Paignton',
    ],
  },
  {
    id: 'cardiff_city_network',
    name: 'Cardiff City Network',
    country: 'UK',
    stations: [
      'Cardiff Central',
      'Cardiff Queen Street',
      'Roath Park',
      'Penylan',
      'Llanishen',
      'Rhiwbina',
      'Whitchurch (Cardiff)',
      'Coryton',
      'Cardiff Bay',
      'Grangetown',
      'Ninian Park',
      'Waun-gron Park',
      'Fairwater',
      'Danescourt',
      'Waun-gron Park',
      'Radyr',
      'Pontypridd',
      'Treforest Estate',
      'Treforest',
      'Taffs Well',
      'Nantgarw',
      'Energlyn & Churchill Park',
      'Caerphilly',
      'Lisvane & Thornhill',
      'Heath Low Level',
      'Heath High Level',
      'Barry Island',
      'Barry',
      'Cadoxton',
      'Dinas Powys',
      'Eastbrook',
      'Cogan',
      'Penarth',
    ],
  },
  {
    id: 'semmeringbahn',
    name: 'Semmeringbahn',
    country: 'AT',
    stations: [
      'Gloggnitz',
      'Payerbach-Reichenau',
      'Küb',
      'Breitenstein',
      'Wolfsbergkogel',
      'Semmering',
      'Spital am Semmering',
      'Mürzzuschlag',
    ],
  },
  {
    id: 'zwolle_groningen',
    name: 'Zwolle–Groningen',
    country: 'NL',
    stations: [
      'Zwolle',
      'Herfte',
      'Lemelerveld',
      'Heino',
      'Raalte',
      'Nijverdal',
      'Hellendoorn',
      'Wierden',
      'Almelo',
      'Vriezenveen',
      'Westerhaar-Vriezenveensewijk',
      'Geerdijk',
      'Hardenberg',
      'Gramsbergen',
      'Coevorden',
      'Emmen',
      'Emmen Zuid',
      'Emmer-Compascuum',
      'Nieuw-Amsterdam',
      'Erica',
      'Klazienaveen',
      'Ter Apel',
      'Musselkanaal',
      'Stadskanaal',
      'Veendam',
      'Scheemda',
      'Winschoten',
      'Zuidbroek',
      'Martenshoek',
      'Hoogezand-Sappemeer',
      'Slochteren',
      'Schildwolde-Kolham',
      'Garmerwolde-Thesinge',
      'Groningen',
    ],
  },
]

export const ROUTE_MAP = Object.fromEntries(ROUTES.map(r => [r.id, r]))

export function getRouteById(id) {
  return ROUTE_MAP[id] ?? null
}

export function getStationsForRoute(routeId) {
  return ROUTE_MAP[routeId]?.stations ?? []
}
